services:
  zf1_test:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysqldb
      - memcachedb
    depends_on:
      - mysqldb
      - memcachedb
    volumes:
     - .:/app
    environment:
      - PHPUNIT=/app/bin/phpunit
      - TMPDIR=/tmp
    working_dir: /app/tests
  memcachedb:
    image: memcached:1.6.5
    ports:
      - 11212:11211
    restart:
      always
  mysqldb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: test
    ports:
      - 3307:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
volumes:
  mysql_db_data_container: